#pragma once
enum bones
{
	BONE_STOMACH = 0x1,
	BONE_UPPER_STOMACH = 0x2,
	BONE_SPINE = 0x3,
	BONE_UPPER_SPINE = 0x4,
	BONE_NECK = 0x5,
	BONE_HEAD = 0x6,
	BONE_LEFT_UPPER_ARM = 0x8,
	BONE_LEFT_LOWER_ARM = 0x9,
	BONE_LEFT_ARM = 0xA,
	BONE_RIGHT_UPPER_ARM = 0xD,
	BONE_RIGHT_LOWER_ARM = 0xE,
	BONE_RIGHT_ARM = 0xF,
	BONE_LEFT_UPPER_LEG = 0x16,
	BONE_LEFT_LOWER_LEG = 0x17,
	BONE_LEFT_ANKLE = 0x18,
	BONE_RIGHT_UPPER_LEG = 0x19,
	BONE_RIGHT_LOWER_LEG = 0x1A,
	BONE_RIGHT_ANKLE = 0x1B,
};

enum HITBOXES : uint32_t
{
	HEAD = 6,
	NECK = 5,
	CHEST = 4,
	RIGHT_CHEST = 8,
	LEFT_CHEST = 13,
	STOMACH = 3,
	PELVIS = 2,
	CENTER = 1,
	L_LEG = 23,
	L_FEET = 24,
	R_LEG = 26,
	R_FEET = 27
};

enum hitboxes
{
	HITBOX_HEAD,
	HITBOX_NECK,
	HITBOX_PELVIS,
	HITBOX_STOMACH,
	HITBOX_CHEST,
	HITBOX_LOWER_CHEST,
	HITBOX_UPPER_CHEST,
	HITBOX_RIGHT_THIGH,
	HITBOX_LEFT_THIGH,
	HITBOX_RIGHT_CALF,
	HITBOX_LEFT_CALF,
	HITBOX_RIGHT_FOOT,
	HITBOX_LEFT_FOOT,
	HITBOX_RIGHT_HAND,
	HITBOX_LEFT_HAND,
	HITBOX_RIGHT_UPPER_ARM,
	HITBOX_RIGHT_FOREARM,
	HITBOX_LEFT_UPPER_ARM,
	HITBOX_LEFT_FOREARM,
	HITBOX_MAX
};

enum hit_group : int32_t
{
	HITGROUP_INVALID = -1,
	HITGROUP_GENERIC,
	HITGROUP_HEAD,
	HITGROUP_CHEST,
	HITGROUP_STOMACH,
	HITGROUP_LEFTARM,
	HITGROUP_RIGHTARM,
	HITGROUP_LEFTLEG,
	HITGROUP_RIGHTLEG,
	HITGROUP_NECK,
	HITGROUP_UNUSED,
	HITGROUP_GEAR,
	HITGROUP_SPECIAL,
	HITGROUP_COUNT,
};

constexpr hit_group hitbox_to_hitgroup_table[HITBOX_MAX] = {
	HITGROUP_HEAD,        // HITBOX_HEAD
	HITGROUP_NECK,        // HITBOX_NECK
	HITGROUP_STOMACH,     // HITBOX_PELVIS
	HITGROUP_STOMACH,     // HITBOX_STOMACH
	HITGROUP_CHEST,       // HITBOX_CHEST
	HITGROUP_CHEST,       // HITBOX_LOWER_CHEST
	HITGROUP_CHEST,       // HITBOX_UPPER_CHEST
	HITGROUP_RIGHTLEG,    // HITBOX_RIGHT_THIGH
	HITGROUP_LEFTLEG,     // HITBOX_LEFT_THIGH
	HITGROUP_RIGHTLEG,    // HITBOX_RIGHT_CALF
	HITGROUP_LEFTLEG,     // HITBOX_LEFT_CALF
	HITGROUP_RIGHTLEG,    // HITBOX_RIGHT_FOOT
	HITGROUP_LEFTLEG,     // HITBOX_LEFT_FOOT
	HITGROUP_RIGHTARM,    // HITBOX_RIGHT_HAND
	HITGROUP_LEFTARM,     // HITBOX_LEFT_HAND
	HITGROUP_RIGHTARM,    // HITBOX_RIGHT_UPPER_ARM
	HITGROUP_RIGHTARM,    // HITBOX_RIGHT_FOREARM
	HITGROUP_LEFTARM,     // HITBOX_LEFT_UPPER_ARM
	HITGROUP_LEFTARM      // HITBOX_LEFT_FOREARM
};

enum move_type : int
{
	MOVETYPE_NONE = 0,
	MOVETYPE_OBSOLETE,
	MOVETYPE_WALK,
	MOVETYPE_FLY,
	MOVETYPE_FLYGRAVITY,
	MOVETYPE_VPHYSICS,
	MOVETYPE_PUSH,
	MOVETYPE_NOCLIP,
	MOVETYPE_OBSERVER,
	MOVETYPE_LADDER,
	MOVETYPE_CUSTOM,
	MOVETYPE_LAST,
	MOVETYPE_MAX_BITS = 5,
};
enum e_protobuf_bits_t : uint32_t {
	protoslot_1 = 1 << 0,
	protoslot_2 = 1 << 1,
	protoslot_3 = 1 << 2,
	protoslot_4 = 1 << 3,
	protoslot_5 = 1 << 4,
	protoslot_6 = 1 << 5,
	protoslot_7 = 1 << 6,
	protoslot_8 = 1 << 7,
	protoslot_9 = 1 << 8,
	protoslot_10 = 1 << 9,
	protoslot_11 = 1 << 10,
	protoslot_12 = 1 << 11,
	protoslot_13 = 1 << 12,
	protoslot_14 = 1 << 13,
	protoslot_15 = 1 << 14,
	protoslot_16 = 1 << 15
};

enum e_button_state : int8_t {
	in_button_up = 0,
	in_button_down = 1,
	in_button_down_up = 2,
	in_button_up_down = 3,
	in_button_up_down_up = 4,
	in_button_down_up_down = 5,
	in_button_down_up_down_up = 6,
	in_button_up_down_up_down = 7
};


#define MULTIPLAYER_BACKUP 150
#define FL_ONGROUND             (1 << 0)   // 1
#define FL_DUCKING              (1 << 1)   // 2
#define FL_WATERJUMP            (1 << 2)   // 4
#define FL_ON_TRAIN             (1 << 3)   // 8
#define FL_IN_RAIN              (1 << 4)   // 16
#define FL_FROZEN               (1 << 5)   // 32
#define FL_AT_CONTROLS          (1 << 6)   // 64
#define FL_CLIENT               (1 << 7)   // 128
#define FL_FAKE_CLIENT          (1 << 8)   // 256


enum ECommandButtons : int
{
	IN_ATTACK = (1 << 0),
	IN_JUMP = (1 << 1),
	IN_DUCK = (1 << 2),
	IN_FORWARD = (1 << 3),
	IN_BACK = (1 << 4),
	IN_USE = (1 << 5),
	IN_CANCEL = (1 << 6),
	IN_LEFT = (1 << 7),
	IN_RIGHT = (1 << 8),
	IN_MOVELEFT = (1 << 9),
	IN_MOVERIGHT = (1 << 10),
	IN_SECOND_ATTACK = (1 << 11),
	IN_RUN = (1 << 12),
	IN_RELOAD = (1 << 13),
	IN_LEFT_ALT = (1 << 14),
	IN_RIGHT_ALT = (1 << 15),
	IN_SCORE = (1 << 16),
	IN_SPEED = (1 << 17),
	IN_WALK = (1 << 18),
	IN_ZOOM = (1 << 19),
	IN_FIRST_WEAPON = (1 << 20),
	IN_SECOND_WEAPON = (1 << 21),
	IN_BULLRUSH = (1 << 22),
	IN_FIRST_GRENADE = (1 << 23),
	IN_SECOND_GRENADE = (1 << 24),
	IN_MIDDLE_ATTACK = (1 << 25),
	IN_USE_OR_RELOAD = (1 << 26)
};

enum ESubtickMoveStepBits : std::uint32_t
{
	MOVESTEP_BITS_BUTTON = 0x1U,
	MOVESTEP_BITS_PRESSED = 0x2U,
	MOVESTEP_BITS_WHEN = 0x4U,
	MOVESTEP_BITS_ANALOG_FORWARD_DELTA = 0x8U,
	MOVESTEP_BITS_ANALOG_LEFT_DELTA = 0x10U
};

enum EInputHistoryBits : std::uint32_t
{
	INPUT_HISTORY_BITS_VIEWANGLES = 0x1U,
	INPUT_HISTORY_BITS_SHOOTPOSITION = 0x2U,
	INPUT_HISTORY_BITS_TARGETHEADPOSITIONCHECK = 0x4U,
	INPUT_HISTORY_BITS_TARGETABSPOSITIONCHECK = 0x8U,
	INPUT_HISTORY_BITS_TARGETANGCHECK = 0x10U,
	INPUT_HISTORY_BITS_CL_INTERP = 0x20U,
	INPUT_HISTORY_BITS_SV_INTERP0 = 0x40U,
	INPUT_HISTORY_BITS_SV_INTERP1 = 0x80U,
	INPUT_HISTORY_BITS_PLAYER_INTERP = 0x100U,
	INPUT_HISTORY_BITS_RENDERTICKCOUNT = 0x200U,
	INPUT_HISTORY_BITS_RENDERTICKFRACTION = 0x400U,
	INPUT_HISTORY_BITS_PLAYERTICKCOUNT = 0x800U,
	INPUT_HISTORY_BITS_PLAYERTICKFRACTION = 0x1000U,
	INPUT_HISTORY_BITS_FRAMENUMBER = 0x2000U,
	INPUT_HISTORY_BITS_TARGETENTINDEX = 0x4000U
};

enum EButtonStatePBBits : uint32_t
{
	BUTTON_STATE_PB_BITS_BUTTONSTATE1 = 0x1U,
	BUTTON_STATE_PB_BITS_BUTTONSTATE2 = 0x2U,
	BUTTON_STATE_PB_BITS_BUTTONSTATE3 = 0x4U
};

enum EBaseCmdBits : std::uint32_t
{
	BASE_BITS_MOVE_CRC = 0x1U,
	BASE_BITS_BUTTONPB = 0x2U,
	BASE_BITS_VIEWANGLES = 0x4U,
	BASE_BITS_COMMAND_NUMBER = 0x8U,
	BASE_BITS_CLIENT_TICK = 0x10U,
	BASE_BITS_FORWARDMOVE = 0x20U,
	BASE_BITS_LEFTMOVE = 0x40U,
	BASE_BITS_UPMOVE = 0x80U,
	BASE_BITS_IMPULSE = 0x100U,
	BASE_BITS_WEAPON_SELECT = 0x200U,
	BASE_BITS_RANDOM_SEED = 0x400U,
	BASE_BITS_MOUSEDX = 0x800U,
	BASE_BITS_MOUSEDY = 0x1000U,
	BASE_BITS_CONSUMED_SERVER_ANGLE = 0x2000U,
	BASE_BITS_CMD_FLAGS = 0x4000U,
	BASE_BITS_ENTITY_HANDLE = 0x8000U
};

enum ECSGOUserCmdBits : std::uint32_t
{
	CSGOUSERCMD_BITS_BASECMD = 0x1U,
	CSGOUSERCMD_BITS_LEFTHAND = 0x2U,
	CSGOUSERCMD_BITS_PREDICTING_BODY_SHOT = 0x4U,
	CSGOUSERCMD_BITS_PREDICTING_HEAD_SHOT = 0x8U,
	CSGOUSERCMD_BITS_PREDICTING_KILL_RAGDOLLS = 0x10U,
	CSGOUSERCMD_BITS_ATTACK3START = 0x20U,
	CSGOUSERCMD_BITS_ATTACK1START = 0x40U,
	CSGOUSERCMD_BITS_ATTACK2START = 0x80U
};
